# Uncomment the next line to define a global platform for your project
# platform :ios, '9.3'

target 'JJSegmentSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JJSegmentSwift
pod 'SnapKit', '~> 4.0.0'

end
